### ISSUE TITLE
TextField labels cover SingleDatePicker

### ISSUE THREAD

**Issue by iDontCYnot** [HealthEngineAU/he-react-ui#17]
Opening the date picker popover causes it to be partially obscured by the labels belonging to the fields below it.
![screen shot 2018-05-23 at 1 34 06 pm](https://user-images.githubusercontent.com/1267049/40405170-05860b2e-5e8e-11e8-91bb-4a92a8aa6912.png)

**Comment by xow** [comment]
Fixed in 29728bee00986646aa8e04f89d24ed6d79126c56
