### ISSUE TITLE
Should yarn.lock be removed

### ISSUE THREAD

**Issue by jradtilbrook** [HealthEngineAU/he-react-ui#5]
Since this is intended as an NPM package, shouldn't yarn.lock be removed and added to .gitignore?

**Comment by xow** [comment]
NPM package, yes, but we use yarn as for the workflow here.

What directory we publish too shouldn't define what tools we use

It's on yarn too if that helps 😛 https://yarnpkg.com/en/package/he-react-ui

**Comment by jradtilbrook** [comment]
As per https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control this is not actually necessary.
